# -*- coding: utf-8 -*-
"""Copy of cansu_özten_midterm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1udYF2Q802HyOVxPnnf30oCDoD5RG9arR

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on 
Drive.
ex: atay_ilgun_MIDTERM.ipynb

Also, create all TD related tasks on one TD file and upload it.
ex: atay_ilgun_MIDTERM.tox
"""





"""Describe what an algorithm is."""

In maths and computer science, an algorithm is an unambigous spefication of how 
to solve a class of problems. Algorithms can perform calculation, data processing and automated reasoning tasks.

"""Explain in what ways algorithmic design is different than the brute-force regular design approach. [50 words]"""

Algorithm Design Paradigms: General approaches to the construction of efficient solutions to problems.Brute force is a straightforward approach to solve a problem based on the problem’s statement and definitions of the concepts involved. It is considered as one of the easiest approach to apply and is useful for solving small – size instances of a problem.

"""In 100 words meditate on how an new approach on design such as one that is algorithmic could affect your work practice."""

Designers make a lot of big and small decisions; many of them are hardly described by clear processes. Moreover, incoming requirements are not 100% clear and consistent, so designers help product managers solve these collisions — making for a better product. It’s much more than about choosing a suitable template and filling it with content.

However, if we talk about creative collaboration, when designers work “in pair” with algorithms to solve product tasks, we see a lot of good examples and clear potential. It’s especially interesting how algorithms can improve our day-to-day work on websites and mobile apps.

"""Create a python dictionary for your name surname and year of birth."""

my_dict = {'key1' :'value1' , 'key2': 'value2'}
dict_cansu = {'name':'cansu','surname':'ozten','year of birth':'1996'}
dict_cansu['surname']

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

name = 'Cansu'
if name[0] == 'a' :
  print ("my initial is a!")
else:
  print("it doesn't")

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

surname = 'Ozten'
len(surname)%3 == 0
if len(surname)%3 == 0 :
  print("it is divisible")
else:
  print("not divisible")

"""Change your year of birth to 2678."""

dict_cansu['year of birth'] = '2678'
print(dict_cansu['year of birth'])



"""TOUCHDESIGNER TIME.

Create a red box [in geo comp] and make it emit particles with a birth rate of 2500.
"""



"""Import a moving image and a sound file in TD.
Add at least two filters to the image file.
Make 2 parameters of these filters responsive to the audio.
"""



"""Create a torus and modify its x-size with an LFO with the frequency of 0.75."""



"""Create a sphere and create an amorph moving shape using 'noise'."""



"""Create a box and apply an image texture on it."""